version: "3.1"

networks:
  net:
    driver: bridge

services:
  db:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER=admin
      POSTGRES_DB=habbit_tracker
      PGDATA = /var/lib/postgresql/data
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - net

  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - net
    environment:
      SERVER_PORT: ":8080"
      DATABASE_CONNECT_STRING: postgresql://admin:secret@localhost:5432/test?sslmode=disable
      LOG_LEVEL: info
      AUTH_JWT_SECRET_KEY: +hd>PywO8jrAnIewJvK7U[bU1;*28m
      AUTH_ACCESS_TOKEN_EXPIRE_MINUTE: 60
