version: "3.1"

networks:
  net:
    driver: bridge

services:
  # mongo:
  #   image: mongo
  #   restart: always
  #   ports:
  #     - "27018:27017"
  #   networks:
  #     - net
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   networks:
  #     - net
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - net
    environment:
      SERVER_PORT: ":8080"
      DATABASE_CONNECT_STRING: mongodb://root:example@mongo:27017/
      DATABAE_NAME: test
      LOG_LEVEL: info
      AUTH_JWT_SECRET_KEY: +hd>PywO8jrAnIewJvK7U[bU1;*28m
      AUTH_ACCESS_TOKEN_EXPIRE_MINUTE: 60
